package com.github.beljaeff.sjb.enums;

public enum BasePermission {
    ADMIN,

    VIEW,

    EDIT_CATEGORY,
    DELETE_CATEGORY,
    ACTIVATE_CATEGORY,

    EDIT_BOARD,
    DELETE_BOARD,
    MOVE_BOARD,
    ACTIVATE_BOARD,

    CREATE_TOPIC,
    EDIT_OWN_TOPIC,
    LOCK_OWN_TOPIC,
    MAKE_STICKY_OWN_TOPIC,
    EDIT_TOPIC,
    DELETE_TOPIC,
    LOCK_TOPIC,
    MAKE_STICKY_TOPIC,
    APPROVE_TOPIC,
    MOVE_TOPIC,
    ACTIVATE_TOPIC,

    CREATE_POST,
    EDIT_OWN_POST,
    MAKE_STICKY_OWN_POST,
    EDIT_POST,
    DELETE_POST,
    MAKE_STICKY_POST,
    APPROVE_POST,
    MOVE_POST,
    ACTIVATE_POST,
    VIEW_ATTACHMENTS,
    CREATE_ATTACHMENTS,
    KARMA_UP_POST,
    KARMA_DOWN_POST,

    ACTIVATE_USER,
    BAN_USER,
    DELETE_USER,

    VIEW_PROFILE,
    EDIT_OWN_PROFILE,
    EDIT_ALL_PROFILES,

    EDIT_USER_GROUP
}
